export const mockTrendsData = [
  // December 2023
  {
    month: "2023-12",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 900000,
  },
  {
    month: "2023-12",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 700000,
  },
  {
    month: "2023-12",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 500000,
  },
  {
    month: "2023-12",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 350000,
  },
  {
    month: "2023-12",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 280000,
  },
  {
    month: "2023-12",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 220000,
  },
  {
    month: "2023-12",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 400000,
  },
  {
    month: "2023-12",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 180000,
  },
  {
    month: "2023-12",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 160000,
  },
  {
    month: "2023-12",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 150000,
  },

  // January 2024
  {
    month: "2024-01",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 1000000,
  },
  {
    month: "2024-01",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 800000,
  },
  {
    month: "2024-01",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 600000,
  },
  {
    month: "2024-01",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 400000,
  },
  {
    month: "2024-01",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 300000,
  },
  {
    month: "2024-01",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 250000,
  },
  {
    month: "2024-01",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 450000,
  },
  {
    month: "2024-01",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 200000,
  },
  {
    month: "2024-01",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 180000,
  },
  {
    month: "2024-01",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 170000,
  },

  // February 2024
  {
    month: "2024-02",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 1200000,
  },
  {
    month: "2024-02",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 850000,
  },
  {
    month: "2024-02",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 650000,
  },
  {
    month: "2024-02",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 450000,
  },
  {
    month: "2024-02",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 320000,
  },
  {
    month: "2024-02",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 280000,
  },
  {
    month: "2024-02",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 500000,
  },
  {
    month: "2024-02",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 220000,
  },
  {
    month: "2024-02",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 190000,
  },
  {
    month: "2024-02",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 160000,
  },

  // March 2024
  {
    month: "2024-03",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 950000,
  },
  {
    month: "2024-03",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 900000,
  },
  {
    month: "2024-03",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 700000,
  },
  {
    month: "2024-03",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 480000,
  },
  {
    month: "2024-03",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 350000,
  },
  {
    month: "2024-03",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 300000,
  },
  {
    month: "2024-03",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 480000,
  },
  {
    month: "2024-03",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 240000,
  },
  {
    month: "2024-03",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 200000,
  },
  {
    month: "2024-03",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 150000,
  },

  // April 2024
  {
    month: "2024-04",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 1100000,
  },
  {
    month: "2024-04",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 1000000,
  },
  {
    month: "2024-04",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 750000,
  },
  {
    month: "2024-04",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 500000,
  },
  {
    month: "2024-04",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 380000,
  },
  {
    month: "2024-04",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 320000,
  },
  {
    month: "2024-04",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 520000,
  },
  {
    month: "2024-04",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 260000,
  },
  {
    month: "2024-04",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 210000,
  },
  {
    month: "2024-04",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 140000,
  },

  // May 2024
  {
    month: "2024-05",
    mechanism_slug: "direct-grants",
    mechanism_name: "Direct Grants",
    value: 1300000,
  },
  {
    month: "2024-05",
    mechanism_slug: "quadratic-funding",
    mechanism_name: "Quadratic Funding",
    value: 1000000,
  },
  {
    month: "2024-05",
    mechanism_slug: "cookie-jar",
    mechanism_name: "Cookie Jar",
    value: 800000,
  },
  {
    month: "2024-05",
    mechanism_slug: "grant-ships",
    mechanism_name: "Grant Ships",
    value: 520000,
  },
  {
    month: "2024-05",
    mechanism_slug: "guilds",
    mechanism_name: "Guilds",
    value: 400000,
  },
  {
    month: "2024-05",
    mechanism_slug: "commitment-pooling",
    mechanism_name: "Commitment Pooling",
    value: 340000,
  },
  {
    month: "2024-05",
    mechanism_slug: "octant-glm-experiment",
    mechanism_name: "Octant GLM Experiment",
    value: 550000,
  },
  {
    month: "2024-05",
    mechanism_slug: "direct-to-contract-incentives",
    mechanism_name: "Direct to Contract Incentives",
    value: 280000,
  },
  {
    month: "2024-05",
    mechanism_slug: "conviction-voting",
    mechanism_name: "Conviction Voting",
    value: 220000,
  },
  {
    month: "2024-05",
    mechanism_slug: "requests-for-proposal6",
    mechanism_name: "Requests for Proposal",
    value: 130000,
  },
];
